apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
spec:
  replicas: 10
  selector:
    matchLabels:
      app: webe
  template:
    metadata:
      labels:
        app: webe
    spec:
      containers:
      - name: webe
        image: vtresposi/ubuntu-install:latest
        ports:
          - containerPort: 80
